config/routes.rb
Markus::Application.routes.draw do
  resources :key_pairs

  # Install the default routes as the lowest priority.
  root controller: 'main', action: 'login', via: [:post, :get]

  # optional path scope (denoted by the parentheses)
  scope '(:locale)', locale: /en|es|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, except: [:new, :edit]
      resources :grade_entry_forms, only: [:show]
      resources :assignments, except: [:new, :edit] do
        resources :groups, except: [:new, :edit] do
          collection do
            get 'group_ids_by_name'
          end
          resources :submission_downloads, except: [:new, :edit]
          resources :feedback_files, except: [:new, :edit]
          resources :test_script_results, except: [:new, :edit] do
            resources :test_results, except: [:new, :edit]
          end
          member do
            post 'add_annotations'
            put 'update_marks'
            put 'update_marking_state'
          end
        end
      end
      resources :main_api
    end

    resources :admins

    resources :assignments do

      collection do
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_feedback_file'
        get 'view_summary'
        get 'populate_file_manager'
        post 'update_files'
        get 'download'
        get 'peer_review'
        get 'summary'
        get 'csv_summary'
      end

      resources :tags do
        collection do
          get 'download_tag_list'
          post 'csv_upload'
          post 'yml_upload'
        end

        member do
          post 'update_tag'
          get 'edit_tag_dialog'
          get 'destroy'
        end
      end

      resources :criteria do
        collection do
          post 'update_positions'
          post 'upload_yml'
          get  'download_yml'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
        end
      end

      resources :exam_templates do
        member do
          get 'download'
          get 'download_generate'
          get 'assign_errors'
          get 'download_raw_split_file'
          get 'download_error_file'
          get 'error_pages'
          patch 'generate'
          patch 'split'
          post 'fix_error'
        end

        collection do
          get 'view_logs'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
        end

        collection do
          get 'populate'
          get 'add_group'
          post 'use_another_assignment_groups'
          get 'manage'
          get 'assign_scans'
          get 'download'
          get 'get_names'
          get 'assign_student_and_next'
          get 'next_grouping'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'populate_file_manager_react'
          get 'populate_submissions_table'
          get 'populate_peer_submissions_table'
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          post 'collect_submissions'
          get 'uncollect_all_submissions'
          post 'run_tests'
          get 'download_svn_export_list'
          get 'download_repo_checkout_commands'
          get 'download_repo_list'
          post 'update_submissions'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          get 'server_time'
          get 'download'
          get 'download_groupings_files'
          get 'check_collect_status'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'edit'
            get 'download'
          end

          member do
            get 'get_annotations'
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            delete 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            post 'set_released_to_students'
            post 'update_overall_comment'
            post 'toggle_marking_state'
            patch 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
            post 'add_tag'
            post 'remove_tag'
            get 'run_tests'
          end
        end
      end

      resources :results, only: [:edit], path: '/peer_reviews' do
        collection do
          get 'download'
          post 'update_mark'
        end

        member do
          get 'view_marks'
          post 'add_extra_mark'
          get 'codeviewer'
          post 'codeviewer'
          get 'next_grouping'
          post 'toggle_marking_state'
          post 'update_mark'
          post 'update_overall_comment'
          patch 'update_remark_request'
        end
      end

      resources :peer_reviews, only: :index do
        collection do
          get 'populate'
          post 'assign_groups'
          get 'download_reviewer_reviewee_mapping'
          post 'csv_upload_handler'
          get 'show_reviews'
        end

        member do
          get 'show_result'
        end
      end

      resources :graders do
        collection do
          get 'populate'
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
          get 'grader_summary'
        end
      end

      resources :annotation_categories do
        member do
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          get 'download'
          post 'yml_upload'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
          get 'find_annotation_text'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'populate_term_marks_table'
        get 'populate_grades_table'
        get 'get_mark_columns'
        get 'view_summary'
        get 'grades'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate_students_table'
          post 'populate_graders_table'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :key_pairs

    resources :course_summaries do
      collection do
        get 'populate'
        get 'get_marking_scheme_details'
        get 'download_csv_grades_report'
        get 'view_summary'
      end
    end

    resources :marking_schemes do
      collection do
        get 'populate'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        patch 'update_annotation'
        delete '/' => 'annotations#destroy'
      end
    end

    resources :students do
      collection do
        patch 'bulk_modify'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'

app/controllers/api/grade_entry_forms_controller.rb
module Api

  class GradeEntryFormsController < MainApiController

    # Sends the contents of the specified grade entry form
    # Requires: id
    def show
      grade_entry_form = GradeEntryForm.find(params[:id])
      send_data grade_entry_form.export_as_csv,
                type: 'text/csv',
                filename: "#{grade_entry_form.short_identifier}_grades_report.csv",
                disposition: 'inline'
    rescue ActiveRecord::RecordNotFound => e
      # could not find grade entry form
      render 'shared/http_status', locals: { code: '404', message: e }, status: 404
    end

  end

end

app/helpers/grade_entry_forms_helper.rb
# Helper methods for grade entry forms

module GradeEntryFormsHelper

  # Release/unrelease the marks for a grade entry form for the given
  # grade_entry_students
  # Return the number of GradeEntryStudents that have been updated successfully
  def set_release_on_grade_entry_students(grade_entry_students, release, errors)
    numGradeEntryStudentsChanged = 0
    grade_entry_students.each do |grade_entry_student|
      begin
        grade_entry_student.released_to_student = release
        unless grade_entry_student.save
          raise I18n.t('grade_entry_forms.grades.update_error',
                       user_name: grade_entry_student.user.user_name)
        end
        numGradeEntryStudentsChanged += 1
      rescue Exception => e
        errors.push(e.message)
      end
    end
    numGradeEntryStudentsChanged
  end

  # Removes items that have empty names (so they don't get updated)
  def update_grade_entry_form_params(attributes)
    grade_entry_items =
      params[:grade_entry_form][:grade_entry_items_attributes]

    unless grade_entry_items.nil?
      # Update the attributes hash
      max_position = 1
      grade_entry_items.each do |_, item|
        # Some items are being deleted so don't update those
        unless item[:_destroy]
          item[:position] = max_position
          max_position += 1
        end
      end
    end
    attributes[:grade_entry_items_attributes] = grade_entry_items
    grade_entry_form_params(attributes)
  end

  def sort_items_by_position(items)
    sorted = items.sort_by { |hsh| hsh[:position] }
  end

  private

  def grade_entry_form_params(attributes)
    attributes.require(:grade_entry_form)
              .permit(:description,
                      :message,
                      :date,
                      :show_total,
                      :short_identifier,
                      :is_hidden,
                      grade_entry_items_attributes: [:name,
                                                     :out_of,
                                                     :position,
                                                     :bonus,
                                                     :_destroy,
                                                     :id])
  end
end

app/views/grade_entry_forms/_form.html.erb
<% # Grade entry creation form
   # #{short_identifier} - An identifier for this grade entry form
   # #{description} - A name for this grade entry form
   # #{message} - Some additional information about this grade entry form
   # #{date} - The date the exam/test/lab corresponding to this grade entry form took place
   # #{grade_entry_item(s)} - Column name and total
%>

<% content_for :head do %>
  <%= stylesheet_link_tag 'jquery-ui' %>
  <%= javascript_include_tag 'moment-with-langs.min' %>

  <%= render partial: 'boot',
             formats: [:js],
             handlers: [:erb] %>
<% end %>

<div class='wrapper'>
  <p><%= t('grade_entry_forms.required_fields').html_safe %></p>
  <%= form_for @grade_entry_form, as: :grade_entry_form do |f| %>

    <%= render partial: 'shared/error_explanation',
               locals: { model: @grade_entry_form } %>

    <fieldset>
      <legend><%= t('grade_entry_forms.properties') %></legend>

      <div>
        <%= f.label :short_identifier, t(:short_identifier),
                    class: 'required' %>
        <%= f.text_field :short_identifier %>
      </div>

      <div>
        <%= f.label :description, t(:description) %>
        <%= f.text_field :description %>
      </div>

      <div>
        <%= f.label :message %>
        <%= f.text_area :message, rows: 8, cols: 65 %>
      </div>

      <div>
        <%= f.label :date, t(:shortened_date) %>
        <%= f.text_field :date,
                         class: 'datepicker',
                         size: 30,
                         placeholder: t('date.formats.date_placeholder') %>
        (<%= label :date_check, t(:remove_date) %>
        <%= check_box_tag :date_check,
                          true,
                          false,
                          disabled: @grade_entry_form.date.blank? %>)
      </div>

      <div>
        <%= f.label :show_total, t('grade_entry_forms.show_total') %>
        <%= f.check_box :show_total %>
      </div>

      <div>
        <%= f.label :is_hidden, t('grade_entry_forms.is_hidden') %>
        <%= f.check_box :is_hidden %>
      </div>

      <% # Display the column names and totals %>
      <div id='grade_entry_items'>
        <% # Ensures there is at least one column whenever the form is loaded. %>
        <% if @grade_entry_form.grade_entry_items.empty? %>
          <%= f.fields_for :grade_entry_items, GradeEntryItem.new do |entry_item| %>
            <%= render partial: 'grade_entry_item',
                       locals: { grade_entry_item: entry_item.object,
                                 form: entry_item } %>
          <% end %>
        <% else %>
          <%= f.fields_for :grade_entry_items do |entry_item| %>
            <%= render partial: 'grade_entry_item',
                       locals: { grade_entry_item: entry_item.object,
                                 form: entry_item } %>
          <% end %>
        <% end %>
      </div>

      <% # Allow the user to add a new column to the form %>
      <%= link_to t('grade_entry_forms.add_column'),
                  '#',
                  onclick: 'add_column(); return false;' %>

    </fieldset>

    <%= f.submit t(f.object.new_record? ? 'grade_entry_forms.create.submit' :
                                          'grade_entry_forms.edit.submit'),
                 data: { disable_with: t('working') } %>
  <% end %>
</div>

app/views/grade_entry_forms/_grade_entry_form_info_summary.html.erb
<p class="due_date">
  <% if grade_entry_form.date %>
    <%= "#{t(:spreadsheet_date)}: #{l(grade_entry_form.date, format: :long_date)}" %>
  <% end %>
</p>

<table>
  <tr>
    <td><%= t(:average) %></td>
    <td>
      <%= number_to_percentage(grade_entry_form.calculate_released_average || 0, precision: 1) %>
    </td>
  </tr>

  <tr>
    <td><%= t(:median) %></td>
    <td>
      <%= number_to_percentage(grade_entry_form.calculate_released_median || 0, precision: 1) %>
    </td>
  </tr>

  <tr>
    <td><%= t(:num_entries) %></td>
    <td>
      <%= "#{grade_entry_form.grade_entry_forms_submitted}/#{grade_entry_form.grade_entry_students.size}" %>
    </td>
  </tr>

  <tr>
    <td><%= t(:num_failed) %></td>
    <td>
      <%= "#{grade_entry_form.calculate_released_failed}" %>
    </td>
  </tr>

  <tr>
    <td><%= t(:num_zeros) %></td>
    <td>
      <%= "#{grade_entry_form.calculate_released_zeros}" %>
    </td>
  </tr>
</table>

app/views/grade_entry_forms/_grade_entry_form_summary.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'Chart', 'chart_config' %>
<% end %>

<% unless @grade_entry_form.nil? %>
    <div class='assignment_summary'>
      <h2 class='title'>
        <%= link_to "#{@grade_entry_form.short_identifier}: #{@grade_entry_form.description}" %>
      </h2>

      <div id='grade_entry_form_<%= @grade_entry_form.id %>_graph' class='left'></div>

      <div class='right'>
        <%= render partial: 'grade_entry_forms/grade_entry_form_info_summary', locals: { grade_entry_form: @grade_entry_form } %>
      </div>

      <br>
      <div id='grade_entry_form_<%= @grade_entry_form.id %>_grade_entry_items_graph' class='ta_grade_distribution'></div>
    </div>
<% end %>

app/views/grade_entry_forms/_grade_entry_item.html.erb
<fieldset class='grade_entry_item'>
  <legend>
    <span><%= t('grade_entry_forms.column') %></span>
  </legend>
  <div>
    <%= form.label :name,
                   t('grade_entry_forms.column_name'),
                   class: 'required' %>
    <%= form.text_field :name, size: 20 %>

    <%= form.label :out_of,
                   t('grade_entry_forms.column_out_of'),
                   class: 'required' %>
    <%= form.text_field :out_of, size: 5, maxlength: 3 %>
  </div>
  <div>
    <%= form.label :bonus, t('grade_entry_forms.bonus_column') %>
    <%= form.check_box :bonus %>
  </div>
  <div>
    <% if !grade_entry_item.nil? && !grade_entry_item.new_record? %>
      <%= form.label :_destroy,
                     t('grade_entry_forms.remove_column') %>
      <%= form.check_box :_destroy %>
    <% else %>
      <%= link_to t(:delete), '#', onclick:
        '$(this).parentsUntil(".grade_entry_item").parent().remove();' +
        'return false;' %>
    <% end %>
  </div>
</fieldset>

app/views/grade_entry_forms/_grade_entry_item_distribution_graph.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'Chart', 'chart_config', 'markus_colors' %>
<% end %>

<% unless grade_entry_items.nil? %>

  <canvas id='grade_entry_form_<%= grade_entry_form.id %>_grade_entry_items' width='400' height='350'></canvas>

  <script>
    // Set up graph
    var ctx = document.getElementById('grade_entry_form_<%= grade_entry_form.id %>_grade_entry_items').getContext('2d');

    // Set up data
    var data = {
      labels: Array.apply(null, Array(21)).map(function (_, i) { return i * 5; }),
      datasets: [
        <% grade_entry_items.each_with_index do |grade_entry_item, index| %>
          {
            label: "<%= grade_entry_item.name %>",
            backgroundColor: colours[<%= index %>],
            data: <%= grade_entry_item.grade_distribution_array(20) %>
          },
        <% end %>
      ]
    };

    var options = {
      tooltips: {
        callbacks: {
          title: function (tooltipItems) {
            var baseNum = parseInt(tooltipItems[0].xLabel);
              if (baseNum === 0) {
                return '0-5';
              } else {
                return (baseNum + 1) + '-' + (baseNum + 5);
              }
          }
        }
      },
      legend: {
        display: true,
        onClick: function(e, legendItem) {
          var index = legendItem.datasetIndex;
          var chart = this.chart;

          for (i = 0, ilen = (chart.data.datasets || []).length; i < ilen; ++i) {
            meta = chart.getDatasetMeta(i);
            if (i == index) {
              meta.hidden = false;
            } else {
              meta.hidden = true;
            }
          }
          chart.update();
        }
      }
    };

    // Draw it
    new Chart(ctx, {
      type: 'bar',
      data: data,
      options: options
    });
  </script>
<% end %>

app/views/grade_entry_forms/_react_grades_table.js.jsx.erb
<script type='text/jsx'>
  /** @jsx React.DOM */
  $(document).ready(function() {
  // Prevent the enter key from releasing grades
    preventEnterSubmit();
  });

  /** This function will prevent the default HTML5 action of submitting the content form
    *  when the user presses "enter". As an Admin user, this would release the grades.
    */
  function preventEnterSubmit() {
    $(document).keypress(function(event) {
      if (event.which === 13) {
        event.preventDefault();
      }
    });
  }

  /** Updates total marks cell. Called from Rails controller grade_entry_forms/update_grade to
    * check if a cell exists before updating it, as cell existence can't be efficiently
    * checked from the Ruby controller
    */
  function update_cell(cell, value) {
    // If the total marks cell exists, change it's value to the one supplied
    if (document.getElementById(cell)) {
      document.getElementById(cell).innerHTML = value;
      var e = new MouseEvent('click', {
        'view': window,
        'bubbles': true,
        'cancelable': false
      });
      var node = document.getElementById(cell);
      node.dispatchEvent(e);
    }
  }

  var GradeBoxTotal = React.createClass({
    handleChange: function() {
      this.props.value = parseFloat(event.target.value, 10);
    },
    render: function() {
      return(
        <span
        id={this.props.grade_id}
        size="4"
        className="grade-total"
        >
        {this.props.value}
        </span>
        );
    }
  });

  var GradeEntryBox = React.createClass({
    componentDidMount: function(){
        this.props.value = this.props.default_value;
    },

    handleChange: function(event) {
      if (this.typing_timer) {
        clearTimeout(this.typing_timer);
      }

      var updated_grade = event.target.value === '' ? null : Number(event.target.value);
      var params = {
        'updated_grade':       updated_grade,
        'student_id':          this.props.student_id,
        'grade_entry_item_id': this.props.grade_entry_column,
        'authenticity_token':  AUTH_TOKEN
      };

      var data_action = this.props.data_action;

      this.typing_timer = setTimeout(function() {
        $.ajax({
          url:  data_action,
          data: params,
          type: 'POST',
          dataType: 'script',
        });
      }, 300);
    },

    // TODO: Make this nicer by not using raw Javascript and jQuery
    handleKeyPress: function(event) {
      if (event.key === 'Enter') {
        var input = this.getDOMNode();
        var td = input.parentNode;
        var tr = td.parentNode;
        var tdIndex = $(tr).children().index(td);
        if (tr.nextSibling !== null) {
          var nextInput = tr.nextSibling.childNodes[tdIndex].firstChild;
          $(nextInput).select()
        }
      }
    },

    render: function() {
      return (
        <input id={this.props.grade_id} type="text" size="4"
          className="grade-input" defaultValue={this.props.default_value}
          onChange={this.handleChange}
          onKeyPress={this.handleKeyPress} />
        );
    }
  });

  var GradesTable = React.createClass({
    getDefaultProps: function() {
      // Creates a new table with the columns defined below.
      // The first column will be the column initially sorted.
      var gradesTable = {
        columns: [
          {
            id: 'user_name',
            content: '<%= j raw I18n.t(:'user.user_name') %>',
            sortable: true,
            searchable: true
          },
          {
            id: 'last_name',
            content: '<%= j raw I18n.t(:'user.last_name') %>',
            sortable: true,
            searchable: true
          },
          {
            id: 'first_name',
            content: '<%= j raw I18n.t(:'user.first_name') %>',
            sortable: true,
            searchable: true
          }
        ],
        filters: [
        {
          name: 'all',
          text: '<%= j raw I18n.t(:'all') %>',
          func: function(student) {
            return true;
          }
        }]
      };
      if (<%= Section.any? %>) {
          gradesTable['columns'].push({
              id: 'section',
              content: '<%= Section.model_name.human %>',
              sortable: true
          });
      }
      return gradesTable;
    },
    getInitialState: function() {
      return {
        row_data: [],
        grade_columns:[],
        selected_students: [],
      }
    },
    updateSelectedStudents: function(students) {
      this.setState({selected_students: students});
    },
    componentWillMount: function() {
      this.refresh();
    },
    refresh: function() {
      document.getElementById('working').style.display = '';

      // Getting additional grade entry item columns
      $.ajax({
        url: 'get_mark_columns',
        method: 'GET',
        dataType: 'json',
        success: function(data) {
          this.setState({
            grade_columns: data,
          });
        }.bind(this),
        // Close working indicator.
        complete: function () {
          document.getElementById('working').style.display = 'none';
        }
      });
      // Getting row data
      $.ajax({
        url: 'populate_grades_table',
        method: 'GET',
        dataType: 'json',
        success: function(data) {
          this.setState({
            row_data: data,
          });
        }.bind(this),
        // Close working indicator.
        complete: function () {
          document.getElementById('working').style.display = 'none';
        }
      });
    },
    render: function() {
      // need to filter for each section
      var sections = <%= raw @sections.to_json %>;
      if (sections.length > 0) {
        var section_filters = sections.map(function(section) {
          var filter = {
            name: section.name,
            text: section.name,
            func: function(group) {
              return group.section === section.name;
            }
          }
          return filter;
        });
        var all = '<%= t('sections.all') %>';
        section_filters.unshift({name: all, text: all, func: null});
      }

      // Add grades and marking state columns to array of table columns
      var all_columns = this.props.columns.concat(this.state.grade_columns);

      // Set React Table data from JSON data
      var rows = this.state.row_data.map(function(row){
        var r = {};
        r['id'] = row.id
        r['user_name'] = row.user_name
        r['first_name'] = row.first_name
        r['last_name'] = row.last_name
        r['section'] = row.section

        this.state.grade_columns.map(function(column){
          var column_id = column.id;

          if (column_id === 'marking_state'){
            if(row[column_id]){
              r[column_id] = <img src={row[column_id]} alt="<%= t('marking_state.released') %>" title="<%= t('marking_state.released') %>"/>;
            }
          }

          else if (column_id === 'total_marks'){
            r[column_id] = <GradeBoxTotal grade_id={'grade_' + row.id + '_' + column.id}
                           grade_entry_column={column.id} student_id={row.id}
                           value={row[column_id]}/>;
          }
          else {
            r[column_id] =
              <GradeEntryBox
               grade_id={'grade_' + row.id + '_' + column.id}
               data_action=
                 "<%= update_grade_grade_entry_form_path(@grade_entry_form) %>"
               grade_entry_column={column.id}
               student_id={row.id}
               default_value={row[column_id]}/>
          }
        }.bind(this));
        return r;
      }.bind(this));
      return (
        <div>
          <GradesActionBox
            selected_students={this.state.selected_students}
            refresh={this.refresh} />
          <Table data={rows}
            search_placeholder={'<%= j raw I18n.t(:'students.search_students') %>'}
            selectable={true} // True if you want checkboxed elements
            onSelectedRowsChange={this.updateSelectedStudents}
            columns={all_columns}
            filters={section_filters}
            filter_type={true}
           />
        </div>
      );
    }
  });

  var GradesActionBox = React.createClass({
    propTypes: {
      selected_students: React.PropTypes.array
    },
    releaseMarks: function() {
      document.getElementById('working').style.display = '';
      var dataLoad = {
        release_results: true,
        filter: 'none',
        students: this.props.selected_students
      };

      $.ajax({
        method: 'POST',
        url: 'update_grade_entry_students',
        data: dataLoad,
        success: function(data) {
          this.props.refresh();
        }.bind(this)
      });
    },
    unreleaseMarks: function() {
      document.getElementById('working').style.display = '';
      var dataLoad = {
        unrelease_results: false,
        filter: 'none',
        students: this.props.selected_students
      };
      $.ajax({
        method: 'POST',
        url: 'update_grade_entry_students',
        data: dataLoad,
        success: function(data) {
          this.props.refresh();
        }.bind(this)
      });
    },
    render: function() {
      return (
        <div class='floatRight'>
          <div className='react-release-marks'>
            <button onClick={this.releaseMarks}>
              <%= j raw I18n.t('browse_submissions.release_marks') %>
            </button>
            <button onClick={this.unreleaseMarks}>
              <%= j raw I18n.t('browse_submissions.unrelease_marks') %>
            </button>
          </div>
        </div>
      );
    }
  });

  React.renderComponent(<GradesTable />, document.getElementById('react_grades_table'));

</script>

app/views/grade_entry_forms/edit.html.erb
<% content_for :title do %>
    <%= t('grade_entry_forms.edit.title') +
           " #{@grade_entry_form.short_identifier}" %>
<% end %>

<%= render partial: 'form' %>

app/views/grade_entry_forms/new.html.erb
<div class='title_bar'>
  <h1><%= t('grade_entry_forms.create.title') %></h1>
</div>

<%= render partial: 'form' %>