config/routes.rb
Markus::Application.routes.draw do
  resources :key_pairs

  # Install the default routes as the lowest priority.
  root controller: 'main', action: 'login', via: [:post, :get]

  # optional path scope (denoted by the parentheses)
  scope '(:locale)', locale: /en|es|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, except: [:new, :edit]
      resources :grade_entry_forms, only: [:show]
      resources :assignments, except: [:new, :edit] do
        resources :groups, except: [:new, :edit] do
          collection do
            get 'group_ids_by_name'
          end
          resources :submission_downloads, except: [:new, :edit]
          resources :feedback_files, except: [:new, :edit]
          resources :test_script_results, except: [:new, :edit] do
            resources :test_results, except: [:new, :edit]
          end
          member do
            post 'add_annotations'
            put 'update_marks'
            put 'update_marking_state'
          end
        end
      end
      resources :main_api
    end

    resources :admins

    resources :assignments do

      collection do
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_feedback_file'
        get 'view_summary'
        get 'populate_file_manager'
        post 'update_files'
        get 'download'
        get 'peer_review'
        get 'summary'
        get 'csv_summary'
      end

      resources :tags do
        collection do
          get 'download_tag_list'
          post 'csv_upload'
          post 'yml_upload'
        end

        member do
          post 'update_tag'
          get 'edit_tag_dialog'
          get 'destroy'
        end
      end

      resources :criteria do
        collection do
          post 'update_positions'
          post 'upload_yml'
          get  'download_yml'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
        end
      end

      resources :exam_templates do
        member do
          get 'download'
          get 'download_generate'
          get 'assign_errors'
          get 'download_raw_split_file'
          get 'download_error_file'
          get 'error_pages'
          patch 'generate'
          patch 'split'
          post 'fix_error'
        end

        collection do
          get 'view_logs'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
        end

        collection do
          get 'populate'
          get 'add_group'
          post 'use_another_assignment_groups'
          get 'manage'
          get 'assign_scans'
          get 'download'
          get 'get_names'
          get 'assign_student_and_next'
          get 'next_grouping'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'populate_file_manager_react'
          get 'populate_submissions_table'
          get 'populate_peer_submissions_table'
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          post 'collect_submissions'
          get 'uncollect_all_submissions'
          post 'run_tests'
          get 'download_svn_export_list'
          get 'download_repo_checkout_commands'
          get 'download_repo_list'
          post 'update_submissions'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          get 'server_time'
          get 'download'
          get 'download_groupings_files'
          get 'check_collect_status'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'edit'
            get 'download'
          end

          member do
            get 'get_annotations'
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            delete 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            post 'set_released_to_students'
            post 'update_overall_comment'
            post 'toggle_marking_state'
            patch 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
            post 'add_tag'
            post 'remove_tag'
            get 'run_tests'
          end
        end
      end

      resources :results, only: [:edit], path: '/peer_reviews' do
        collection do
          get 'download'
          post 'update_mark'
        end

        member do
          get 'view_marks'
          post 'add_extra_mark'
          get 'codeviewer'
          post 'codeviewer'
          get 'next_grouping'
          post 'toggle_marking_state'
          post 'update_mark'
          post 'update_overall_comment'
          patch 'update_remark_request'
        end
      end

      resources :peer_reviews, only: :index do
        collection do
          get 'populate'
          post 'assign_groups'
          get 'download_reviewer_reviewee_mapping'
          post 'csv_upload_handler'
          get 'show_reviews'
        end

        member do
          get 'show_result'
        end
      end

      resources :graders do
        collection do
          get 'populate'
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
          get 'grader_summary'
        end
      end

      resources :annotation_categories do
        member do
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          get 'download'
          post 'yml_upload'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
          get 'find_annotation_text'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'populate_term_marks_table'
        get 'populate_grades_table'
        get 'get_mark_columns'
        get 'view_summary'
        get 'grades'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate_students_table'
          post 'populate_graders_table'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :key_pairs

    resources :course_summaries do
      collection do
        get 'populate'
        get 'get_marking_scheme_details'
        get 'download_csv_grades_report'
        get 'view_summary'
      end
    end

    resources :marking_schemes do
      collection do
        get 'populate'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        patch 'update_annotation'
        delete '/' => 'annotations#destroy'
      end
    end

    resources :students do
      collection do
        patch 'bulk_modify'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :noteable, polymorphic: true, counter_cache: true

  validates_presence_of :notes_message, :creator_id, :noteable

  belongs_to :user, foreign_key: :creator_id, counter_cache: true
  validates_associated :user

  NOTEABLES = %w(Grouping Student Assignment)

  def user_can_modify?(current_user)
    current_user.admin? || user == current_user
  end

  def format_date
    I18n.l(created_at, format: :long_date)
  end

  def self.noteables_exist?
    NOTEABLES.each do |classname|
      unless Kernel.const_get(classname).all.empty?
        return true
      end
    end
    false
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authorize_for_ta_and_admin
  before_filter :ensure_can_modify, only: [:edit, :update]

  # TODO this method needs explaining ! What is return_id ?
  def notes_dialog
    @return_id = params[:id]
    @cls = params[:noteable_type]
    @noteable = Kernel.const_get(@cls).find_by_id(params[:noteable_id])
    @cont = params[:controller_to]
    @action = params[:action_to]
    @highlight_field = params[:highlight_field]
    @number_of_notes_field = params[:number_of_notes_field]

    @notes = Note.where(noteable_id: @noteable.id, noteable_type: @noteable.class.name)

    render partial: 'notes/modal_dialogs/notes_dialog_script',
      formats: [:js], handlers: [:erb]
  end

  def add_note
    return unless request.post?
    @note = Note.new
    @note.creator_id = @current_user.id
    @note.notes_message = params[:new_notes]
    @note.noteable_id = params[:noteable_id]
    @note.noteable_type = params[:noteable_type]
    unless @note.save
      render 'notes/modal_dialogs/notes_dialog_error',
        formats: [:js], handlers: [:erb]
    else
      @note.reload
      @number_of_notes_field = params[:number_of_notes_field]
      @highlight_field = params[:highlight_field]
      @number_of_notes = @note.noteable.notes.size
      render 'notes/modal_dialogs/notes_dialog_success',
        formats: [:js], handlers: [:erb]
    end
  end

  def index
    @notes = Note.includes(:user, :noteable).order(created_at: :desc)
    @current_user = current_user
    # Notes are attached to noteables, if there are no noteables, we can't make notes.
    @noteables_available = Note.noteables_exist?
		render 'index', formats: [:html]
  end

  # gets the objects for groupings on first load.
  def new
    new_retrieve
    @note = Note.new
		render 'new', formats: [:html], handlers: [:erb]
  end

  def create
    @note = Note.new(notes_params)
    @note.noteable_type = params[:noteable_type]
    @note.creator_id = @current_user.id

    if @note.save
      flash_message(:success, I18n.t('notes.create.success'))
      redirect_to action: 'index'
    else
      new_retrieve
      render 'new', formats: [:html], handlers: [:erb]
    end
  end

  # Used to update the values in the groupings dropdown in the new note form
  def new_update_groupings
    retrieve_groupings(Assignment.find(params[:assignment_id]))
    render 'new_update_groupings', formats: [:js], handlers: [:erb]
  end

  # used for RJS call
  def noteable_object_selector
    case params[:noteable_type]
      when 'Student'
        @students = Student.order(:user_name)
      when 'Assignment'
        @assignments = Assignment.all
      when 'Grouping'
        new_retrieve
      else
        # default to groupings if all else fails.
        params[:noteable_type] = 'Grouping'
        flash_message(:error, I18n.t('notes.new.invalid_selector'))
        new_retrieve
    end
		render 'noteable_object_selector', formats: [:js], handlers: [:erb]
  end

  def edit
		render 'edit', formats: [:html], handlers: [:erb]
  end

  def update
    if @note.update_attributes(notes_params)
      flash_message(:success, I18n.t('notes.update.success'))
      redirect_to action: 'index'
    else
      render 'edit', formats: [:html], handlers: [:erb]
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user_can_modify?(current_user)
      @note.destroy
      flash_message(:success, I18n.t('notes.delete.success'))
    else
      flash_message(:error, I18n.t('notes.delete.error_permissions'))
    end
	  render 'destroy', formats: [:js], handlers: [:erb]
  end

  private

    def retrieve_groupings(assignment)
      if assignment.nil?
        @groupings = Array.new
        return
      end
      @groupings = Grouping.includes(:group, student_memberships: :user).where(assignment_id: assignment.id)
    end

    def new_retrieve
      @assignments = Assignment.all
      retrieve_groupings(@assignments.first)
    end

    # Renders a 404 error if the current user can't modify the given note.
    def ensure_can_modify
      @note = Note.find(params[:id])

      unless @note.user_can_modify?(current_user)
        render 'shared/http_status', formats: [:html], status: 404,
          layout: false, locals: {
            code: '404', message: HttpStatusHelper::ERROR_CODE['message']['404']
          }
      end
    end

  def notes_params
    params.require(:note).permit(:notes_message, :noteable_id)
  end
end

app/views/notes/_assignment.html.erb
<%= fields_for :note do |f| %>
  <p>
    <%= f.label :noteable_id, t('notes.noteables.Assignment')%>
    <%= f.select :noteable_id, @assignments.map { |item| [item.short_identifier, item.id] }%>
  </p>
<% end %>

app/views/notes/_grouping.html.erb
<%= fields_for :note do |f| %>
  <p>
    <%= label_tag 'assignment_id', t('notes.noteables.Assignment') %>
    <%= select_tag 'assignment_id',
                   options_from_collection_for_select(@assignments,
                                                      :id,
                                                      :short_identifier),
                   onchange: "document.getElementById('working').style.display = '';
                              $.ajax({
                                url: '" + new_update_groupings_notes_path + "',
                                type: 'POST',
                                data: $(this).serialize() + '&authenticity_token=' + AUTH_TOKEN
                              }).done(function() {
                                document.getElementById('working').style.display = 'none';
                              });" %>
  </p>
  <p>
    <%= f.label :noteable_id, t('notes.noteables.Grouping') %>
    <%= f.select :noteable_id, @groupings.collect { |p| [p.group_name_with_student_user_names,p.id] } %>
  </p>
<% end %>

app/views/notes/_student.html.erb
<%= fields_for :note do |f| %>
  <p>
    <%= f.label :noteable_id, t('notes.noteables.Student') %>
    <%= f.select :noteable_id, @students.collect { |p| [p.user_name,p.id] } %>
  </p>
<% end %>

app/views/notes/destroy.js.erb
document.location.reload();

app/views/notes/edit.html.erb
<%= render partial: 'shared/navigation_warning',
           formats: [:js],
           handlers: [:erb] %>

<div class='title_bar'>
  <h1><%= t('notes.edit.title')%></h1>
</div>

<div class='wrapper'>
  <%= form_for @note, as: :note, url: { action: 'update', id: @note.id } do |f| %>
    <%= render partial: 'shared/error_explanation',
               locals: { model: @note } %>

    <table>
      <tr>
        <td>
          <strong><%= t('notes.author')%>:</strong>
        </td>
        <td>
          <%= @note.user.user_name %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%= t("notes.noteables.#{@note.noteable_type}") %>:</strong>
        </td>
        <td>
          <%= @note.noteable.display_for_note %>
        </td>
      </tr>
      <tr>
        <td>
          <strong><%=t('notes.creation_time')%>:</strong>
        </td>
        <td>
          <%= @note.format_date %>
        </td>
      </tr>
    </table>

    <p>
      <%= raw(f.label :notes_message,
                      t('notes.note')) %>:
      <%= raw(f.text_area :notes_message,
                          rows: 10,
                          onchange: 'set_onbeforeunload(true);') %>
    </p>

    <%= f.submit t('save'),
                 data: { disable_with: t('working') },
                 onclick: 'set_onbeforeunload(false);' %>
    <%= link_to t('cancel'), notes_path(), class: 'button' %>

  <% end %>
</div>

app/views/notes/index.html.erb
<div class='title_bar'>
  <h1>
    <%= t('notes.title') %>
    <span class='title-help notes_help'>
      <p class='help-message-title notes_help'>
        <%= t('notes.help') %>
      </p>
    </span>
  </h1>
</div>

<div class='wrapper'>

  <%= render 'shared/flash_message' %>

  <%# If there are no noteables,we can't add notes, so do not show Add New link. %>
  <% if @noteables_available %>
    <%= link_to t('notes.add_new'),
                { action: 'new' },
                class: 'button' %>
  <% else %>
    <p><%= t('notes.new.no_noteables') %></p>
  <% end %>

  <div class='table'>
    <table id='notes'>
      <thead>
        <tr>
          <th><%= t('notes.existing') %></th>
          <th><%= t('notes.new.note_message') %></th>
          <th><%= t('actions') %></th>
        </tr>
      </thead>
      <% for note in @notes %>
        <tr>
          <td>
            <%= raw(t('notes.note_on',
                    user_name: note.user.user_name,
                    display_for: note.noteable.display_for_note )) %>
            <br>
            <small><%= note.format_date %></small>
          </td>
          <td><%= note.notes_message %></td>
          <td>
            <% if note.user_can_modify?(@current_user) %>
              <%= button_to t('edit'),
                            edit_note_path(note.id),
                            method: 'get',
                            html: { class: 'edit' },
                            class: 'inline-button' %>
              <%= button_to t('delete'),
                            { action: 'destroy',
                              id: note.id },
                            html: { class: 'delete',
                                    title: t('notes.delete.link_title') },
                            data: { confirm: t('notes.delete.link_confirm') },
                            method: 'delete',
                            remote: true,
                            class: 'inline-button' %>
            <% else %>
              &nbsp;
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/notes/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'notes' %>
<% end %>

<%= render partial: 'shared/navigation_warning',
           formats: [:js],
           handlers: [:erb] %>

<div class='title_bar'>
  <h1><%= t('notes.new.title') %></h1>
</div>

<div class='wrapper'>
  <%= form_for @note, as: :note, url: notes_path do |f| %>
    <%= render partial: 'shared/error_explanation',
               locals: { model: @note } %>

    <p id='noteable_type'>
      <%= label_tag 'noteable_type', t('notes.noteable') %>
      <%= select_tag 'noteable_type',
                     options_for_select(
                        Note::NOTEABLES.map { |item| [t('notes.noteables.' + item),
                                                      item ]}) %>
    </p>

    <div id='noteable_selector'>
      <%= render partial: 'grouping' %>
    </div>

    <p>
      <%= raw(f.label :notes_message, t('notes.note')) %>
      <%= raw(f.text_area :notes_message,
                          rows: 10,
                          onchange: 'set_onbeforeunload(true);') %>
    </p>

    <%= f.submit t('save'),
                 onclick: 'set_onbeforeunload(false);',
                 data: { disable_with: t('working') } %>
    <%= link_to t('cancel'), notes_path, class: 'button' %>

  <% end %>
</div>

app/views/notes/new_update_groupings.js.erb
$('#note_noteable_id').html('<%= escape_javascript(options_from_collection_for_select(@groupings, :id, :group_name_with_student_user_names)).html_safe %>');

app/views/notes/noteable_object_selector.js.erb
$('#noteable_selector').html('<%= escape_javascript(
             render partial: params[:noteable_type].downcase).html_safe %>');