config/routes.rb
Markus::Application.routes.draw do
  resources :key_pairs

  # Install the default routes as the lowest priority.
  root controller: 'main', action: 'login', via: [:post, :get]

  # optional path scope (denoted by the parentheses)
  scope '(:locale)', locale: /en|es|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, except: [:new, :edit]
      resources :grade_entry_forms, only: [:show]
      resources :assignments, except: [:new, :edit] do
        resources :groups, except: [:new, :edit] do
          collection do
            get 'group_ids_by_name'
          end
          resources :submission_downloads, except: [:new, :edit]
          resources :feedback_files, except: [:new, :edit]
          resources :test_script_results, except: [:new, :edit] do
            resources :test_results, except: [:new, :edit]
          end
          member do
            post 'add_annotations'
            put 'update_marks'
            put 'update_marking_state'
          end
        end
      end
      resources :main_api
    end

    resources :admins

    resources :assignments do

      collection do
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_feedback_file'
        get 'view_summary'
        get 'populate_file_manager'
        post 'update_files'
        get 'download'
        get 'peer_review'
        get 'summary'
        get 'csv_summary'
      end

      resources :tags do
        collection do
          get 'download_tag_list'
          post 'csv_upload'
          post 'yml_upload'
        end

        member do
          post 'update_tag'
          get 'edit_tag_dialog'
          get 'destroy'
        end
      end

      resources :criteria do
        collection do
          post 'update_positions'
          post 'upload_yml'
          get  'download_yml'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
        end
      end

      resources :exam_templates do
        member do
          get 'download'
          get 'download_generate'
          get 'assign_errors'
          get 'download_raw_split_file'
          get 'download_error_file'
          get 'error_pages'
          patch 'generate'
          patch 'split'
          post 'fix_error'
        end

        collection do
          get 'view_logs'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
        end

        collection do
          get 'populate'
          get 'add_group'
          post 'use_another_assignment_groups'
          get 'manage'
          get 'assign_scans'
          get 'download'
          get 'get_names'
          get 'assign_student_and_next'
          get 'next_grouping'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'populate_file_manager_react'
          get 'populate_submissions_table'
          get 'populate_peer_submissions_table'
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          post 'collect_submissions'
          get 'uncollect_all_submissions'
          post 'run_tests'
          get 'download_svn_export_list'
          get 'download_repo_checkout_commands'
          get 'download_repo_list'
          post 'update_submissions'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          get 'server_time'
          get 'download'
          get 'download_groupings_files'
          get 'check_collect_status'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'edit'
            get 'download'
          end

          member do
            get 'get_annotations'
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            delete 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            post 'set_released_to_students'
            post 'update_overall_comment'
            post 'toggle_marking_state'
            patch 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
            post 'add_tag'
            post 'remove_tag'
            get 'run_tests'
          end
        end
      end

      resources :results, only: [:edit], path: '/peer_reviews' do
        collection do
          get 'download'
          post 'update_mark'
        end

        member do
          get 'view_marks'
          post 'add_extra_mark'
          get 'codeviewer'
          post 'codeviewer'
          get 'next_grouping'
          post 'toggle_marking_state'
          post 'update_mark'
          post 'update_overall_comment'
          patch 'update_remark_request'
        end
      end

      resources :peer_reviews, only: :index do
        collection do
          get 'populate'
          post 'assign_groups'
          get 'download_reviewer_reviewee_mapping'
          post 'csv_upload_handler'
          get 'show_reviews'
        end

        member do
          get 'show_result'
        end
      end

      resources :graders do
        collection do
          get 'populate'
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
          get 'grader_summary'
        end
      end

      resources :annotation_categories do
        member do
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          get 'download'
          post 'yml_upload'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
          get 'find_annotation_text'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'populate_term_marks_table'
        get 'populate_grades_table'
        get 'get_mark_columns'
        get 'view_summary'
        get 'grades'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate_students_table'
          post 'populate_graders_table'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :key_pairs

    resources :course_summaries do
      collection do
        get 'populate'
        get 'get_marking_scheme_details'
        get 'download_csv_grades_report'
        get 'view_summary'
      end
    end

    resources :marking_schemes do
      collection do
        get 'populate'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        patch 'update_annotation'
        delete '/' => 'annotations#destroy'
      end
    end

    resources :students do
      collection do
        patch 'bulk_modify'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'

app/helpers/groups_helper.rb
module GroupsHelper
  # Gets information needed to display students
  # in the table on the front-end. Returns
  # an array of hashes.
  def get_students_table_info
    students = Student.all
    student_memberships = StudentMembership
                          .includes(:user)
                          .where(grouping_id: @assignment.groupings)

    students_in_assignment = student_memberships.map do |membership|
      membership.user
    end

    students.map do |student|
      s = student.attributes
      s['assigned'] = students_in_assignment.include?(student)
      s
    end
  end

  # Gets information needed to display group info
  # on the front-end. Attributes include URLs for actions
  # such as validation, renaming, showing notes, etc.
  def get_groupings_table_info(target_assignment=nil)
    if target_assignment.nil?
      target_assignment = @assignment
    end

    groupings = target_assignment.groupings
                           .includes(:group,
                                     :student_memberships,
                                     :non_rejected_student_memberships,
                                     :students,
                                     :inviter)
    groupings.map do |grouping|
      g = grouping.attributes
      g[:name] = grouping.group.group_name
      g[:members] = grouping.student_memberships.map {|membership| [membership.user.id, membership.user.user_name, membership.membership_status]}#grouping.students
      g[:section] = grouping.section
      g[:valid] = grouping.is_valid?
      g[:validate_link] = view_context.link_to(
        view_context.image_tag(
          'icons/cross.png',
          alt: I18n.t('groups.is_not_valid'),
          title: I18n.t('groups.is_not_valid')),
          valid_grouping_assignment_groups_path(
            grouping_id: grouping.id),
          confirm:  I18n.t('groups.validate_confirm'),
        remote: true)

      g[:invalidate_link] = view_context.link_to(
        view_context.image_tag(
          'icons/tick.png',
          alt: I18n.t('groups.is_valid'),
          title: I18n.t('groups.is_valid')),
        invalid_grouping_assignment_groups_path(
          grouping_id: grouping.id),
          confirm:  I18n.t('groups.invalidate_confirm'),
        remote: true)

      rename_link = rename_group_assignment_group_path(target_assignment, grouping)
      g[:rename_link] = view_context.link_to(
        view_context.image_tag(
          'icons/pencil.png',
          alt: I18n.t('groups.rename_group.link'),
          title: I18n.t('groups.rename_group.link')),
        'javascript:void(0);',
        onclick:"modal_rename.open();"\
                "$('#rename_group_dialog form').attr('action', '#{rename_link}')")

      g[:note_link] = view_context.link_to(
        view_context.image_tag(
          'icons/note.png',
          alt: I18n.t('notes.title'),
          title: I18n.t('notes.title')),
        notes_dialog_note_path(
          id: target_assignment.id,
          noteable_id: grouping.id,
          noteable_type: 'Grouping',
          action_to: 'note_message',
          controller_to: 'groups'),
        remote: true)

      g[:delete_link] = view_context.link_to(
        view_context.image_tag(
          'icons/bin_closed.png',
          alt: I18n.t('groups.delete')),
        remove_group_assignment_groups_path(
          grouping_id:  grouping.id),
        method: 'delete',
        confirm:  I18n.t('groups.delete_confirm'),
        remote: true)
      g
    end
  end
end

app/views/groups/_assignment_group_use_modal.html.erb
<%= content_for :modal_id, 'assignment_group_use_dialog' %>
<%= content_for :modal_title, t('groups.reuse_groups') %>
<%= content_for :modal_content do %>
    <%= form_tag use_another_assignment_groups_assignment_groups_path(@assignment) do %>
        <%= label_tag :clone_assignment_id, t('groups.assignment_to_use') %>
        <%= select_tag :clone_assignment_id,
                       options_for_select(
                           @clone_assignments.map {|a| [a.short_identifier, a.id]}) %>
        <section class='dialog-actions'>
          <%= submit_tag t(:submit),
                         data: { disable_with: t(:working),
                                 confirm: t('groups.delete_groups_linked') } %>
          <%= button_tag t(:cancel), type: 'button', onclick:'modalAssignmentGroupReUse.close()' %>
        </section>
    <% end %>
<% end %>

app/views/groups/_create_group_modal.html.erb
<%= content_for :modal_id, 'create_group_dialog' %>
<%= content_for :modal_title, t('groups.create_new_group') %>
<%= content_for :modal_content do %>
    <%= form_tag new_assignment_group_path(@assignment),
                 method: :get,
                 remote: true do %>
        <%= label_tag :new_group_name, t('groups.group_name') %>
        <%= text_field_tag :new_group_name,
                           '',
                           maxlength: 30 %>
        <section class='dialog-actions'>
          <%= submit_tag t('groups.create_new_group') %>
          <%= button_tag t(:cancel), onclick:'modalCreate.close()' %>
        </section>
    <% end %>
<% end %>

app/views/groups/_delete_errors.html.erb
<ul>
  <% group_names.each do |group_name| %>
    <li><%= group_name %></li>
  <% end %>
</ul>

app/views/groups/_download_modal.html.erb
<%= content_for :modal_id, 'download_dialog' %>
<%= content_for :modal_title, t('groups.download.download_groups_file') %>
<%= content_for :modal_open_link, '#downloadModal' %>

<%= content_for :modal_content do %>

  <div class='clickable_links'>
    <div class='clickable_text'>
      <img class='clickable_image' src='<%= image_url('icons/download-file.png') %>'>
      <%= t('download_csv') %>
    </div>
    <%= link_to '',
                { action: 'download_grouplist',
                  id: @groups },
                class: 'make_div_clickable' %>
  </div>
  <section class='dialog-actions'>
    <input type='reset' id='download' value='<%= t(:cancel) %>'/>
  </section>
<% end %>

app/views/groups/_groups_manager.js.jsx.erb
<script type='text/jsx'>
  /** @jsx React.DOM */

  // The master component that manages both tables and
  // the add/remove actions
  var GroupsManager = React.createClass({
    getInitialState: function() {
      return {
        students: [],
        selected_students: [],
        groups: [],
        selected_groups: [],
        selected_students_in_groups: []
      };
    },
    componentWillMount: function() {
      this.refresh();
    },
    updateSelectedStudents: function(students) {
      this.setState({selected_students: students});
    },
    updateSelectedGroups: function(groups) {
      this.setState({selected_groups: groups});
    },
    updateSelectedStudentsInGroups: function(students) {
      this.setState({selected_students_in_groups: students});
    },
    // Sends a request to the server to perform some action
    // such as assigning or removing a member to/from a group
    // todo: function should be moved to actions column (separation of concerns)
    performAction: function(action) {
      var dataLoad = {
        submit_type: 'global_action',
        global_actions: action,
        students: this.state.selected_students,
        students_to_remove: this.state.selected_students_in_groups,
        groupings: this.state.selected_groups
      };

      $.ajax({
        method: 'POST',
        url: 'groups/global_actions',
        data: dataLoad,
        success: function(data) {
          this.refresh();
          this.refs.groupsStudentsTable.clearCheckboxes();
          this.refs.groupsTable.clearCheckboxes();
          this.setState({
            selected_students: [],
            selected_groups: [],
            selected_students_in_groups: [],
          });
        }.bind(this),
      });
    },
    componentDidMount: function () {
      var me = this;
      $(document).ready(function () {
        $('#create_group_dialog form').on('ajax:success', function() {
          modalCreate.close();
          me.refresh();
        });
      });
    },
    // Asks for new info from backend and sets state accordingly.
    refresh: function() {
      document.getElementById('working').style.display = '';

      $.ajax({
        url: 'groups/populate',
        method: 'GET',
        dataType: 'json',
        success: function(data) {
          document.getElementById('working').style.display = 'none';
          this.setState({
            students: data[0],
            groups: data[1]
          });
        }.bind(this)
      });
    },
    render: function() {
      return (
        <div>
          <div className='columns'>
            <GroupsStudentsTable ref="groupsStudentsTable"
              students={this.state.students}
              selected_students={this.state.selected_students}
              onSelectedStudentsChange={this.updateSelectedStudents} />
            <GroupsActionsColumn refresh={this.refresh} performAction={this.performAction} />
            <GroupsTable ref="groupsTable"
              groups={this.state.groups}
              selected_groups={this.state.selected_groups}
              onSelectedGroupsChange={this.updateSelectedGroups}
              selected_students_in_groups={this.state.selected_students_in_groups}
              onSelectedStudentsInGroupsChange={this.updateSelectedStudentsInGroups}
              refresh={this.refresh} />
          </div>
        </div>
      );
    }
  });

  // Table of students, on the left.
  var GroupsStudentsTable = React.createClass({
    getDefaultProps: function() {
      return {
        columns: [
          {
            id: 'user_name',
            content: '<%= j raw I18n.t('user.user_name') %>',
            sortable: true,
            searchable: true
          },
          {
            id: 'last_name',
            content: '<%= j raw I18n.t('user.last_name') %>',
            sortable: true,
            searchable: true,
          },
          {
            id: 'first_name',
            content: '<%= j raw I18n.t('user.first_name') %>',
            sortable: true,
            searchable: true
          }
        ],
        filters: [
          {
            name: 'all',
            text: '<%= j raw I18n.t('groups.all_students') %>',
            func: function(student) {
              return student;
            }
          },
          {
            name: 'unassigned',
            text: '<%= j raw I18n.t('groups.unassigned_students') %>',
            func: function(student) {
              return !student.assigned;
            }
          },
          {
            name: 'assigned',
            text: '<%= j raw I18n.t('groups.assigned_students') %>',
            func: function(student) {
              return student.assigned;
            }
          },
          {
            name: 'inactive',
            text: '<%= j raw I18n.t('groups.inactive_students') %>',
            func: function(student) {
              return student.hidden;
            }
          }
        ]
      };
    },
    clearCheckboxes: function() {
      this.refs.table.clearCheckboxes();
    },
    render: function() {
      var students_data = this.props.students.map(function(student) {
        var s = {};
        s['id'] = student.id;
        s['user_name'] = student.user_name;
        s['last_name'] = student.last_name;
        s['first_name'] = student.first_name;
        s['hidden'] = student.hidden;
        s['assigned'] = student.assigned;
        return s;
      }.bind(this));

      return (
        <div className={'col-left'} >
          <div className={'tab-pane ui-tabs ui-widget ui-widget-content ui-corner-all'} id='students-tabs'>
            <Table ref="table"
                   data={students_data}
                   columns={this.props.columns}
                   filters={this.props.filters}
                   selectable={true}
                   onSelectedRowsChange={this.props.onSelectedStudentsChange}
                   search_placeholder={'<%= j raw I18n.t('students.search_students') %>'} />
          </div>
        </div>
      );
    }
  });

  // The table of groups on the right.
  var GroupsTable = React.createClass({
    getDefaultProps: function() {
      return {
        columns: [
          {
            id: 'name',
            content: '<%= j raw I18n.t('groups.group_name') %>',
            sortable: true,
            searchable: true
           },
           {
             id: 'links',
             content: '<%= j raw I18n.t('actions') %>',
             sortable: false,
             searchable: false
           },
           {
             id: 'members',
             content: '<%= j raw I18n.t('members') %>',
             sortable: false,
             searchable: false
           },
        ],
        filters: [
          {
            name: 'all',
            text: '<%= j raw I18n.t('groups.all_grouping_counts') %>',
            func: function(group) {
              return true;
            }
          },
          {
            name: 'valid',
            text: '<%= j raw I18n.t('groups.valid_grouping_counts') %>',
            func: function(group) {
              return group.valid;
            }
          },
          {
            name: 'not_valid',
            text: '<%= j raw I18n.t('groups.not_valid_grouping_counts') %>',
            func: function(group) {
            return !group.valid;
            }
          },
        ]
      };
    },
    studentCheckboxClicked: function(event) {
      var value = event.currentTarget.checked;
      var group_student_id = parseInt(event.currentTarget.getAttribute('id'), 10);
      var new_selected_students_in_groups = this.props.selected_students_in_groups.slice();
      if (value) {
        new_selected_students_in_groups.push(group_student_id);
      } else {
        new_selected_students_in_groups.splice(new_selected_students_in_groups.indexOf(group_student_id), 1);
      }
      this.props.onSelectedStudentsInGroupsChange(new_selected_students_in_groups);
    },
    clearCheckboxes: function() {
      this.refs.table.clearCheckboxes();
    },
    render: function() {
      var filters = [
      {
        name: 'all',
        text: '<%= j raw I18n.t('groups.all_grouping_counts') %>',
        func: function(group) {
          return true;
        }
      },
      {
        name: 'valid',
        text: '<%= j raw I18n.t('groups.valid_grouping_counts') %>',
        func: function(group) {
          return group.valid;
        }
      },
      {
        name: 'not_valid',
        text: '<%= j raw I18n.t('groups.not_valid_grouping_counts') %>',
        func: function(group) {
        return !group.valid;
        }
      },
      ];

      // Massage the data so it will fit into the table.
      var groups_data = this.props.groups.map(function(group) {
        var g = {};
        g['id'] = group.id;
        <% if @assignment.scanned_exam %>
        g['name'] = <a href={Routes.assign_scans_assignment_groups_path({assignment_id: <%= @assignment.id %>, grouping: group.id})}>{group.name}</a>;
        <% else %>
        g['name'] = group.name;
        <% end %>
        var links = [];
        if (group.valid) {
          links.push(group.invalidate_link);
        } else {
          links.push(group.validate_link);
        }
        links.push(group.rename_link);
        links.push(group.note_link);
        links.push(group.delete_link);
        g['links'] = <span onClick={this.props.refresh} dangerouslySetInnerHTML={{__html: links.join(' ')}} ></span>

        var members = [];
        for (var i = 0; i < group.members.length; i++) {
          var member_name = group.members[i][1];
          var member_status = group.members[i][2];
          var member_string;
          if (member_status.toLowerCase() === 'pending') {
            member_string = <b>{member_name} ({member_status})</b>
          } else {
            member_string = member_name + ' (' + member_status + ')'
          }
          members.push(
            <div key={group.members[i][0]}>
              <input id={group.members[i][0]}
                type='checkbox'
                checked={this.props.selected_students_in_groups.indexOf(group.members[i][0]) !== -1}
                onChange={this.studentCheckboxClicked}
              />
              {member_string}
            </div>
          );
        }
        g['members'] = members;
        g['valid'] = group.valid;

        return g;
      }.bind(this));

      return (
        <div className={'col-right'}>
          <div className={'tab-pane ui-tabs ui-widget ui-widget-content ui-corner-all'} id='groups-tabs'>
            <AddGroupButton refresh={this.props.refresh} />
            <% if @assignment.group_max == 1 && !@assignment.scanned_exam %>
              <%= button_to t('groups.add_all_groups'),
                            { action: 'create_groups_when_students_work_alone',
                              id: @assignment.id },
                            method: :get, remote: true %>
            <% end %>
            <Table ref="table"
              data={groups_data}
              columns={this.props.columns}
              filters={this.props.filters}
              selectable={true}
              onSelectedRowsChange={this.props.onSelectedGroupsChange}
              search_placeholder={'<%= j raw I18n.t('groups.search_groups') %>'} />
          </div>
        </div>
      );
    }
  });

  var AddGroupButton = React.createClass({
    <% if @assignment.group_name_autogenerated %>
      createGroup: function() {
        $.ajax({
          method: 'GET',
          url: '<%= new_assignment_group_path(@assignment) %>',
        });
      },
    <% else %>
      createGroup: function() {
        modalCreate.open();
        $('#new_group_name').val('');
        return false;
      },
    <% end %>
    render: function() {
      return (
        <button className='floatRight' onClick={this.createGroup} >
          <%= t('groups.add_new') %>
        </button>
      );
    }
  });

  var GroupsActionsColumn = React.createClass({
    performAction: function(event) {
      var action = event.currentTarget.getAttribute('id');
      this.props.performAction(action);
    },
    render: function() {
      return (
        <div className={'col-center'}>
          <div id='icons'>
            <input id='assign'
              className='image_input'
              src='<%= image_path('add_arrow.png') %>'
              alt='<%= j raw I18n.t('add_members') %>'
              onClick={this.performAction}
              type='image'
            />
            <input id='unassign'
              className='image_input'
              src='<%= image_path('remove_arrow.png') %>'
              alt='<%= j raw I18n.t('remove_members') %>'
              onClick={this.performAction}
              type='image'
            />
          </div>
        </div>
      );
    }
  });
  React.renderComponent(<GroupsManager />, document.getElementById('groups_manager'));
</script>

app/views/groups/_join.html.erb
<%= form_tag controller: 'groups', action: 'join', id: @assignment.id do %>
  <p>
    <b><%= @group.inviter.user_name %></b> has invited you to join his group
    for assignment <b><%= sanitize(@assignment.short_identifier) %></b>.
  </p>

  <p>Would you like to accept this invitation?</p>

  <%= submit_tag "Accept", name: 'accept' %>
  <%= submit_tag "Reject", name: 'reject',
    confirm: "Are you sure? This will make you create your own group" %>
<% end -%>

app/views/groups/_rename_group_modal.html.erb
<%= content_for :modal_id, 'rename_group_dialog' %>
<%= content_for :modal_title, t('groups.rename_group.title') %>
<%= content_for :modal_content do %>
    <%= form_tag '', remote: true do %>
        <%= label_tag :new_groupname, t('groups.rename_group.group_name') %>
        <%= text_field_tag :new_groupname, '', maxlength: 30 %>
        <section class='dialog-actions'>
          <%= submit_tag t('groups.rename_group.title') %>
          <input type='reset' value='<%= t(:cancel) %>' onclick='modal_rename.close();' />
        </section>
    <% end %>
<% end %>

app/views/groups/_update_progress_bar.js.erb
function update_bar(score, outof) {
  var width = outof <= 0 ? 100 : (score/outof) * 100;
  var $bar = $('.progress_span');
  $bar.text(score + '/' + outof + ' <%= t('complete') %>');
  $bar.css('width', width + '%');
  if (width > 75) {
    $bar.css('background-color', 'green')
  } else if (width > 35) {
    $bar.css('background-color', '#FBC02D')
  }
}

app/views/groups/_upload_modal.html.erb
<%= content_for :modal_id, 'upload_dialog' %>
<%= content_for :modal_title, t('groups.upload.upload_groups_file') %>
<%= content_for :modal_open_link, '#uploadModal' %>

<%= content_for :modal_content do %>

  <!-- Script for disabling upload buttons. -->
  <%= javascript_include_tag 'upload_button_control.js',
                             id: 'upload_script',
                             upload_id: 'group_grouplist',
                             button_id: 'upload' %>

  <p>
    <%= t('groups.upload.description').html_safe %>
    <% if !@assignment.groupings.nil? && @assignment.groupings.length > 0 %>
      <div class='information'>
        <%= t('groups.upload.importing') %>
      </div>
  <% end %>
  </p>
  <%= form_for :group, html: {multipart: true},
               url: { controller:'groups',
                      action: 'csv_upload',
                      id: @assignment.id } do |f| %>
    <p>
      <%= label_tag t('encoding') %>
      <%= select_tag(:encoding, options_for_select(@encodings)) %>
    </p>
    <%= f.file_field :grouplist, size: 2 %>

    <section class='dialog-actions'>
      <%= submit_tag t(:upload),
                     data: { disable_with: t(:uploading_please_wait) },
                     disabled: true,
                     id: 'upload' %>
      <input type='reset' value='<%= t(:cancel) %>'/>
    </section>
  <% end %>
<% end %>