config/routes.rb
Markus::Application.routes.draw do
  resources :key_pairs

  # Install the default routes as the lowest priority.
  root controller: 'main', action: 'login', via: [:post, :get]

  # optional path scope (denoted by the parentheses)
  scope '(:locale)', locale: /en|es|fr|pt/  do
    # API routes
    namespace :api do
      resources :users, except: [:new, :edit]
      resources :grade_entry_forms, only: [:show]
      resources :assignments, except: [:new, :edit] do
        resources :groups, except: [:new, :edit] do
          collection do
            get 'group_ids_by_name'
          end
          resources :submission_downloads, except: [:new, :edit]
          resources :feedback_files, except: [:new, :edit]
          resources :test_script_results, except: [:new, :edit] do
            resources :test_results, except: [:new, :edit]
          end
          member do
            post 'add_annotations'
            put 'update_marks'
            put 'update_marking_state'
          end
        end
      end
      resources :main_api
    end

    resources :admins

    resources :assignments do

      collection do
        get 'delete_rejected'
        post 'update_collected_submissions'
        get 'download_assignment_list'
        post 'upload_assignment_list'
      end

      member do
        get 'refresh_graph'
        get 'student_interface'
        post 'invite_member'
        get 'creategroup'
        get 'join_group'
        get 'deletegroup'
        get 'decline_invitation'
        post 'disinvite_member'
        get 'render_feedback_file'
        get 'view_summary'
        get 'populate_file_manager'
        post 'update_files'
        get 'download'
        get 'peer_review'
        get 'summary'
        get 'csv_summary'
      end

      resources :tags do
        collection do
          get 'download_tag_list'
          post 'csv_upload'
          post 'yml_upload'
        end

        member do
          post 'update_tag'
          get 'edit_tag_dialog'
          get 'destroy'
        end
      end

      resources :criteria do
        collection do
          post 'update_positions'
          post 'upload_yml'
          get  'download_yml'
        end
      end

      resources :automated_tests do
        collection do
          get 'manage'
          post 'update' # because of collection
          post 'update_positions'
          get 'update_positions'
          post 'upload'
          get 'download'
        end
      end

      resources :exam_templates do
        member do
          get 'download'
          get 'download_generate'
          get 'assign_errors'
          get 'download_raw_split_file'
          get 'download_error_file'
          get 'error_pages'
          patch 'generate'
          patch 'split'
          post 'fix_error'
        end

        collection do
          get 'view_logs'
        end
      end

      resources :groups do

        member do
          post 'rename_group'
        end

        collection do
          get 'populate'
          get 'add_group'
          post 'use_another_assignment_groups'
          get 'manage'
          get 'assign_scans'
          get 'download'
          get 'get_names'
          get 'assign_student_and_next'
          get 'next_grouping'
          post 'csv_upload'
          get 'add_csv_group'
          get 'download_grouplist'
          get 'create_groups_when_students_work_alone'
          get 'valid_grouping'
          get 'invalid_grouping'
          get 'global_actions'
          get 'rename_group'
          delete 'remove_group'
          post 'add_group'
          post 'global_actions'
        end
      end

      resources :submissions do
        collection do
          get 'populate_file_manager_react'
          get 'populate_submissions_table'
          get 'populate_peer_submissions_table'
          get 'file_manager'
          get 'browse'
          post 'populate_file_manager'
          post 'collect_submissions'
          get 'uncollect_all_submissions'
          post 'run_tests'
          get 'download_svn_export_list'
          get 'download_repo_checkout_commands'
          get 'download_repo_list'
          post 'update_submissions'
          get 'updated_files'
          get 'replace_files'
          get 'delete_files'
          post 'update_files'
          get 'server_time'
          get 'download'
          get 'download_groupings_files'
          get 'check_collect_status'
        end

        member do
          get 'collect_and_begin_grading'
          post 'manually_collect_and_begin_grading'
          get 'repo_browser'
          post 'repo_browser'
          get 'downloads'
        end

        resources :results do
          collection do
            post 'update_mark'
            get 'edit'
            get 'download'
          end

          member do
            get 'get_annotations'
            get 'add_extra_marks'
            get 'add_extra_mark'
            get 'download'
            post 'download'
            get 'download_zip'
            delete 'cancel_remark_request'
            get 'codeviewer'
            post 'codeviewer'
            post 'add_extra_mark'
            post 'delete_grace_period_deduction'
            get 'next_grouping'
            post 'remove_extra_mark'
            post 'set_released_to_students'
            post 'update_overall_comment'
            post 'toggle_marking_state'
            patch 'update_remark_request'
            get 'update_positions'
            post 'update_mark'
            get 'view_marks'
            post 'add_tag'
            post 'remove_tag'
            get 'run_tests'
          end
        end
      end

      resources :results, only: [:edit], path: '/peer_reviews' do
        collection do
          get 'download'
          post 'update_mark'
        end

        member do
          get 'view_marks'
          post 'add_extra_mark'
          get 'codeviewer'
          post 'codeviewer'
          get 'next_grouping'
          post 'toggle_marking_state'
          post 'update_mark'
          post 'update_overall_comment'
          patch 'update_remark_request'
        end
      end

      resources :peer_reviews, only: :index do
        collection do
          get 'populate'
          post 'assign_groups'
          get 'download_reviewer_reviewee_mapping'
          post 'csv_upload_handler'
          get 'show_reviews'
        end

        member do
          get 'show_result'
        end
      end

      resources :graders do
        collection do
          get 'populate'
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_groupings_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
          get 'grader_summary'
        end
      end

      resources :annotation_categories do
        member do
          delete 'delete_annotation_text'
          get 'add_annotation_text'
          post 'add_annotation_text'
          put 'update_annotation'
        end

        collection do
          post 'update_positions'
          post 'csv_upload'
          get 'download'
          post 'yml_upload'
          get 'add_annotation_text'
          post 'delete_annotation_text'
          post 'update_annotation'
          get 'find_annotation_text'
        end
      end
    end

    resources :grade_entry_forms do
      collection do
        get 'student_interface'
      end

      member do
        get 'populate_term_marks_table'
        get 'populate_grades_table'
        get 'get_mark_columns'
        get 'view_summary'
        get 'grades'
        get 'csv_download'
        post 'csv_upload'
        post 'update_grade'
        post 'update_grade_entry_students'
        get 'student_interface'
      end

      resources :marks_graders do
        collection do
          get 'add_grader_to_grouping'
          post 'csv_upload_grader_groups_mapping'
          post 'csv_upload_grader_criteria_mapping'
          get 'download_grader_students_mapping'
          get 'download_grader_criteria_mapping'
          get 'download_dialog'
          get 'download_grouplist'
          get 'grader_criteria_dialog'
          get 'global_actions'
          get 'groups_coverage_dialog'
          post 'populate_graders'
          post 'populate_students_table'
          post 'populate_graders_table'
          post 'populate'
          post 'populate_criteria'
          post 'set_assign_criteria'
          get 'random_assign'
          get 'upload_dialog'
          get 'unassign'
          post 'global_actions'
        end
      end

    end

    resources :notes do

      collection do
        post 'add_note'
        post 'noteable_object_selector'
        get 'new_update_groupings'
        post 'new_update_groupings'
      end

      member do
        get 'student_interface'
        get 'notes_dialog'
        post 'grades'
      end
    end

    resources :key_pairs

    resources :course_summaries do
      collection do
        get 'populate'
        get 'get_marking_scheme_details'
        get 'download_csv_grades_report'
        get 'view_summary'
      end
    end

    resources :marking_schemes do
      collection do
        get 'populate'
      end
    end

    resources :sections

    resources :annotations do
      collection do
        post 'add_existing_annotation'
        patch 'update_annotation'
        delete '/' => 'annotations#destroy'
      end
    end

    resources :students do
      collection do
        patch 'bulk_modify'
        get 'manage'
        get 'add_new_section'
        get 'download_student_list'

app/models/result.rb
class Result < ApplicationRecord

  MARKING_STATES = {
    complete: 'complete',
    incomplete: 'incomplete'
  }

  belongs_to :submission
  has_many :marks
  has_many :extra_marks
  has_many :annotations
  has_many :peer_reviews

  after_create :create_marks
  validates_presence_of :marking_state
  validates_inclusion_of :marking_state, in: MARKING_STATES.values

  validates_numericality_of :total_mark, greater_than_or_equal_to: 0

  before_update :unrelease_partial_results
  before_save :check_for_nil_marks

  scope :submitted_remarks_and_all_non_remarks, lambda {
    results = Result.arel_table
    where(results[:remark_request_submitted_at].eq(nil))
  }

  # Returns a list of total marks for each student whose submissions are graded
  # for the assignment specified by +assignment_id+, sorted in ascending order.
  # This includes duplicated marks for each student in the same group (marks
  # are given for a group, so each student in the same group gets the same
  # mark).
  def self.student_marks_by_assignment(assignment_id)
    # Need to get a list of total marks of students' latest results (i.e., not
    # including old results after having remarked results). This is a typical
    # greatest-n-per-group problem and can be implemented using a subquery
    # join.
    subquery = Result.select('max(results.id) max_id')
      .joins(submission: {grouping: {student_memberships: :user}})
      .where(groupings: {assignment_id: assignment_id},
             users: {hidden: false},
             submissions: {submission_version_used: true},
             marking_state: Result::MARKING_STATES[:complete])
      .group('users.id')
    Result.joins("JOIN (#{subquery.to_sql}) s ON id = s.max_id")
      .order(:total_mark).pluck(:total_mark)
  end

  # Calculate the total mark for this submission
  def update_total_mark
    user_visibility = is_a_review? ? :peer : :ta
    update_attributes(total_mark:
      [0, get_subtotal(user_visibility) + get_total_extra_points +
          get_total_extra_percentage_as_points(user_visibility)].max)
  end

  # The sum of the marks not including bonuses/deductions
  def get_subtotal(user_visibility = :ta)
    if marks.empty?
      0
    else
      assignment = submission.grouping.assignment
      criteria = assignment.get_criteria(user_visibility).map { |c| [c.class.to_s, c.id] }
      marks_array = (marks.to_a.select { |m| criteria.member? [m.markable_type, m.markable_id] }).map &:mark
      marks_array.sum || 0
    end
  end

  # The sum of the bonuses and deductions, other than late penalty
  def get_total_extra_points
    extra_marks.points.map(&:extra_mark).reduce(0, :+).round(1)
  end

  # The sum of all the positive extra marks
  def get_positive_extra_points
    extra_marks.positive.points.map(&:extra_mark).reduce(0, :+).round(1)
  end

  # The sum of all the negative extra marks
  def get_negative_extra_points
    extra_marks.negative.points.map(&:extra_mark).reduce(0, :+).round(1)
  end

  # Percentage deduction for late penalty
  def get_total_extra_percentage
    extra_marks.percentage.map(&:extra_mark).reduce(0, :+).round(1)
  end

  # Point deduction for late penalty
  def get_total_extra_percentage_as_points(user_visibility = :ta)
    (get_total_extra_percentage * submission.assignment.max_mark(user_visibility) / 100).round(1)
  end

  # un-releases the result
  def unrelease_results
    self.released_to_students = false
    self.save
  end

  def mark_as_partial
    return if self.released_to_students
    self.marking_state = Result::MARKING_STATES[:incomplete]
    self.save
  end

  def is_a_review?
    !peer_review_id.nil?
  end

  def is_review_for?(user, assignment)
    grouping = user.grouping_for(assignment.id)
    pr = PeerReview.find_by(result_id: self.id)
    !pr.nil? && submission.grouping == grouping
  end

  def create_marks
    assignment = self.submission.assignment
    assignment.get_criteria(:ta).each do |criterion|
      mark = criterion.marks.create(result_id: id)
    end
    self.update_total_mark
  end

  # Returns a hash of all marks for this result.
  # TODO: make it include extra marks as well.
  def mark_hash
    Hash[
      marks.map do |mark|
        ["criterion_#{mark.markable_type}_#{mark.markable_id}",
         mark.mark]
      end
    ]
  end

  private
  # If this record is marked as "partial", ensure that its
  # "released_to_students" value is set to false.
  def unrelease_partial_results
    unless is_a_review?
      if marking_state != MARKING_STATES[:complete]
        self.released_to_students = false
      end
    end
    true
  end

  def check_for_nil_marks(user_visibility = :ta)
    # This check is only required when the marking state is complete.
    return true unless marking_state == Result::MARKING_STATES[:complete]

    # peer review result is a special case because when saving a pr result
    # we can't pass in a parameter to the before_save filter, so we need
    # to manually determine the visibility. If it's a pr result, we know we
    # want the peer-visible criteria
    visibility = is_a_review? ? :peer : user_visibility

    criteria = submission.assignment.get_criteria(visibility).map { |c| [c.class.to_s, c.id] }
    nil_marks = false
    num_marks = 0
    marks.each do |mark|
      if criteria.member? [mark.markable_type, mark.markable_id]
        num_marks += 1
        if mark.mark.nil?
          nil_marks = true
          break
        end
      end
    end

    if nil_marks || num_marks < criteria.count
      errors.add(:base, I18n.t('common.criterion_incomplete_error'))
      return false
    end
    true
  end
end

app/helpers/results_helper.rb
module ResultsHelper

  def remark_result_unsubmitted_or_released(remark_result)
    remark_result.marking_state == Result::MARKING_STATES[:incomplete] ||
      remark_result.released_to_students
  end

  def can_show_remark_request_tab_in_student_pane(assignment,
                                                  current_user,
                                                  submission,
                                                  result)
    if result.is_a_review?
      return false
    else
      if assignment.allow_remarks
        if submission.remark_result &&
           submission.remark_result.released_to_students
          return true
        else
          return current_user.student?
        end
      else
        false
      end
    end
  end

  def student_can_edit_remark_request(submission)
    !submission.remark_result ||
      submission.remark_result.marking_state ==
        Result::MARKING_STATES[:incomplete]
  end

  def can_show_remark_request_tab_in_marker_pane(submission)
    submission.remark_submitted?
  end

  def can_show_feedback_files_tab?(submission)
    not submission.feedback_files.empty?
  end

  def create_nested_files_hash_table(files)
    # arrange the files list into a nested hashtable for displaying in a recursive menu
    outermost_dir = Hash.new
    files.each do |file|
      innermost_dir = outermost_dir
      innermost_dir[:files] = Array.new
      folders = file.path.split('/')
      folders.each do |folder_name|
        unless innermost_dir.key?(folder_name)
          innermost_dir[folder_name] = Hash.new
          innermost_dir[folder_name][:files] = Array.new
        end
        innermost_dir = innermost_dir[folder_name]
      end
      innermost_dir[:files].push(file)
    end
    outermost_dir
  end
end

app/views/results/_download_modal.html.erb
<%= content_for :modal_id, 'download_dialog' %>
<%= content_for :modal_title, t('download') %>
<%= content_for :modal_open_link, '#downloadModal' %>

<%= content_for :modal_content do %>

  <%= render partial: 'results/common/download_file_selector',
             locals: { files: @files,
                       can_download: true } %>
  <% if can_show_feedback_files_tab?(@submission) %>
    <div id='feedback_files_controls'>
      <%= render partial: 'results/common/feedback_file_selector',
                 locals: { feedback_files: @feedback_files,
                           submission_id: @submission.id } %>
    </div>
  <% end %>
  <section class='dialog-actions'>
    <input type='reset' id="download" value='<%= t(:cancel) %>'/>
  </section>
<% end %>

app/views/results/_result_summary.html.erb
<div id='result_summary' class='flex-col'>
  <%= render partial: 'results/student/student_panes',
             locals: { extra_marks_points: extra_marks_points,
                       extra_marks_percentage: extra_marks_percentage,
                       result: @result,
                       mark_criteria: @mark_criteria,
                       marks_map: @marks_map,
                       old_marks_map: @old_marks_map,
                       assignment: @assignment,
                       submission: @submission,
                       old_result: @old_result,
                       files: @files,
                       feedback_files: @feedback_files} %>
</div>

app/views/results/delete_grace_period_deduction.js.erb
document.getElementById('submission_rule_viewer').innerHTML =
  '<%= escape_javascript(render partial: @grouping.assignment.submission_rule.grader_tab_partial,
                                locals: { grouping: @grouping }).html_safe %>';

app/views/results/edit.html.erb
<% content_for :head do %>
  <%# TODO: merge 'grader.scss' into 'results.scss' %>
  <%= stylesheet_link_tag 'result_main' %>
  <%# MathML %>
  <%= javascript_include_tag 'MathJax_lib/MathJax.js?config=TeX-AMS-MML_HTMLorMML' %>
  <%= javascript_include_tag 'MathJax/mathjax_helpers', defer: true %>
  <%= javascript_pack_tag 'result' %>
    <script>
    document.addEventListener('DOMContentLoaded', () => {
      window.annotationTable =
        makeAnnotationTable(document.getElementById('annotation_table'),
          {
            result_id: <%= @result.id %>,
            submission_id: <%= @result.submission_id %>,
            assignment_id: <%= @result.submission.grouping.assignment_id %>,
            detailed: <%= @current_user.admin? || @current_user.ta? ||
                          @current_user.is_reviewer_for?(@assignment.pr_assignment, @result) %>
          }
      );

      <% unless @result.released_to_students || @current_user.is_reviewer_for?(@assignment.pr_assignment, @result) %>
      window.annotationManager =
        makeAnnotationManager(document.getElementById('annotation_options'),
          {
            result_id: <%= @result.id %>,
            submission_id: <%= @result.submission_id %>,
            assignment_id: <%= @result.submission.grouping.assignment_id %>,
          }
        );
      <% end %>
    });
  </script>
<% end %>

<script>
  var modalNotesGroup = null;

  $(document).ready(function() {
    localStorage.setItem('assignment_id', <%= @result.submission.grouping.assignment_id %>);
    window.modalNotesGroup = new ModalMarkus('#notes_dialog');
    window.modal_download = new ModalMarkus('#download_files_dialog');
    window.modal_help = new ModalMarkus('#help_dialog');

    // Set up the 'working' notices
    $('#working').ajaxStart(function() {
      this.style.display = '';
      window.onbeforeunload = check_working;
    }).ajaxStop(function() {
      this.style.display = 'none';
      window.onbeforeunload = null;
    });

    // If the mark_description div is empty, that means it isn't marked
    // Hide the criterion that AREN'T empty (i.e. are marked)
    // Check if the marks are released, if they are there is nothing to hide
    <% unless @result.released_to_students %>
      $('.mark_criterion_level_container').each(function() {
        expand_unmarked(this, 'RubricCriterion');
      });
      $('.mark_grade_input').each(function() {
        expand_unmarked(this, 'FlexibleCriterion');
      });
      $('.mark_grade_input_checkbox_container').each(function() {
        expand_unmarked(this, 'CheckboxCriterion');
      });
    <% end %>

    <%
      if @current_user.admin?
        num_marked = @assignment.get_num_marked
        num_assigned = @assignment.get_num_assigned
      else
        num_marked = @assignment.get_num_marked(@current_user.id)
        num_assigned = @assignment.get_num_assigned(@current_user.id)
      end
    %>
    update_bar(<%= num_marked %>, <%= num_assigned %>);

    <%= render partial: 'results/marker/keybinding',
               formats: [:js] %>
  });

  function check_working() {
    return '<%= t(:still_working_warning) %>';
  }
</script>

<% # Javascript for showing/hiding old marks %>
<%= render partial: 'results/common/old_marks_view_functions',
           formats: [:html] %>

<% # Javascript for feedback file window %>
<%= render partial: 'assignments/feedback_file_window',
           formats: [:js] %>

<% # Javascript for progress bar %>
<%= render partial: 'results/marker/update_progress_bar',
           formats: [:js] %>

<%= render partial: 'results/common/annotations',
           formats: [:js],
           locals: {
             result_id: @result.id,
             assignment_id: @result.submission.grouping.assignment.id
           } %>

<%= render partial: 'results/marker/boot',
           formats: [:js],
           locals: { first_file: @files.first } %>

<!-- Dialogs -->
<aside class='dialog' id='notes_dialog' style='display:none'></aside>
<aside class='dialog' id='download_files_dialog' style='display:none'>
  <h1><%= 'Download Files' %></h1>

  <%= render partial: 'results/common/download_file_selector',
             locals: { files: @files,
                       can_download: true } %>

</aside>
<aside class='dialog' id='help_dialog' style='display:none'>
  <h1><%=t('keybinding.keyboard_help')%></h1>
  <table class="help_table">
    <tr>
      <td><kbd>Alt</kbd> + <kbd>Enter/return</kbd></td>
      <td><%=t('keybinding.toggle_compact')%></td>
    </tr>
    <tr>
      <td><kbd>Shift</kbd> + <kbd>⇨</kbd></td>
      <td><%=t('keybinding.next_submission')%></td>
    </tr>
    <tr>
      <td><kbd>Shift</kbd> + <kbd>⇦</kbd></td>
      <td><%=t('keybinding.previous_submission')%></td>
    </tr>
    <tr>
      <td><kbd>Shift</kbd> + <kbd>⇧</kbd></td>
      <td><%=t('keybinding.previous_criterion')%></td>
    </tr>
    <tr>
      <td><kbd>Shift</kbd> + <kbd>⇩</kbd></td>
      <td><%=t('keybinding.next_criterion')%></td>
    </tr>
    <tr>
      <td><kbd>⇧</kbd></td>
      <td><%=t('keybinding.when_rubric') + t('keybinding.previous_level')%></td>
    </tr>
    <tr>
      <td><kbd>⇩</kbd></td>
      <td><%=t('keybinding.when_rubric') + t('keybinding.next_level')%></td>
    </tr>
    <tr>
      <td><kbd>Enter/return</kbd></td>
      <td><%=t('keybinding.when_rubric') + t('keybinding.confirm_level')%></td>
    </tr>
    <tr>
      <td><kbd>Shift</kbd> + <kbd>n</kbd></td>
      <td><%=t('keybinding.open_annotation')%></td>
    </tr>
    <tr>
      <td><kbd>Cmd/Ctrl</kbd> + <kbd>Enter/return</kbd></td>
      <td><%=t('keybinding.confirm_annotation')%></td>
    </tr>
  </table>
</aside>
<% if @current_user.admin? %>
  <aside class='dialog' id='create_new_tag' style='display:none'>
    <h1><%= t('tags.create.create_new') %></h1>
    <p><%= t('tags.create.tag_prompt') %></p>
    <%= form_for :create_new,
                 url: assignment_tags_path(@assignment),
                 html: { multipart: true } do |f| %>
        <div>
          <p><%= f.text_field :name,
                              placeholder: t('tags.create.name_prompt') %></p>
        </div>
        <div>
          <p class='alignleft'><%= t('tags.create.tag_description') %></p>
          <p id='descript_amount' class='alignright'>0/120</p>
          <p class="clear-alignment"><%= f.text_area :description,
                                                  id: 'description',
                                                  cols: 30,
                                                  rows: 3,
                                                  maxlength: 120,
                                                  onKeyDown: 'updateCharCount()',
                                                  placeholder: t('tags.create.descript_prompt') %></p>
        </div>
        <section class='dialog-actions'>
          <%= hidden_field_tag 'grouping_id', @grouping.id %>
          <%= f.submit t('tags.create.button_text') %>
          <input type='reset'
                 value='<%= t(:cancel) %>'
                 onclick='modal_create_new.close();'>
        </section>
    <% end %>
  </aside>
  <aside class='dialog' id='delete_tags' style='display:none'>
    <h1><%= t('tags.delete.delete_tags') %></h1>
    <p><%= t('tags.delete.tag_prompt') %></p>
    <%= form_for :delete,
                 url: assignment_tags_path(@assignment),
                 html: { multipart: true } do |f| %>

    <% end %>
    <input type='reset'
           value='<%= t(:cancel) %>'
           onclick='modal_delete_tags.close();'>
  </aside>
<% end %>

<% content_for :title do %>
  <%= t('results.title',
        { assignment_name: @assignment.short_identifier,
          group_name: @current_user.student? ? t('assignment.review') : @grouping.get_group_name }) %>
<% end %>
<% content_for :additional_headings do %>
  <div class="progress_meter">
    <span class="progress_span">
    </span>
  </div>
  <a onclick="compact_view_toggle()" style="margin: 0px 15px">Compact View</a>
<% end %>

<div class='wrapLeft'>
  <% if flash[:fail_notice] %>
    <p class='error'><%= flash[:fail_notice] %></p>
  <% end %>

  <% if @result.released_to_students %>
    <p class='notice'><%= t(:marks_released_notice) %></p>
  <% end %>

  <% if @grouping.past_due_date? %>
    <p class='warning'>
      <%= t(:past_due_date_edit_result_warning,
            href: link_to(t(:last_commit),
                          repo_browser_assignment_submission_path(
                             @assignment, @grouping))).html_safe %>
    </p>
  <% end %>

  <%= render partial: 'results/common/submission_selector',
             locals: { group: @group,
                       result: @result,
                       assignment: @assignment,
                       previous_grouping: @previous_grouping,
                       next_grouping: @next_grouping } %>

  <%= render partial: 'results/common/errors' %>

  <% if !@result.released_to_students %>
    <%= render partial: 'results/marker/marker_panes',
               locals: { extra_marks_points: @result.extra_marks.points,
                         extra_marks_percentage: @result.extra_marks.percentage,
                         annotation_categories:
                           @assignment.annotation_categories.includes(annotation_texts: [:user]),
                         result: @result,
                         assignment: @assignment,
                         marks_map: @marks_map,
                         old_marks_map: @old_marks_map,
                         mark_criteria:@mark_criteria,
                         submission: @submission,
                         old_result: @old_result,
                         test_results: @test_results,
                         files: @files,
                         feedback_files: @feedback_files} %>
  <% else %>
    <%= render partial: 'results/result_summary',
               formats: [:html],
               handlers: [:erb],
               locals: { extra_marks_points: @result.extra_marks.points,
                         extra_marks_percentage: @result.extra_marks.percentage
               }
    %>
  <% end %>
</div>

<%# Javascript files %>
<%= javascript_include_tag 'Results/main' %>

<!-- load the first file -->
<script>
  var first_file_id;
  var first_file_path;
  <% if @files.empty? %>
    first_file_id = null;
    first_file_path = null;
  <% else %>
    <% if @current_user.ta? && (assignmentfile =
              AssignmentFile.select(:filename)
              .joins('JOIN criteria_assignment_files_joins c ON c.assignment_file_id = assignment_files.id')
              .joins('JOIN criterion_ta_associations t ON c.criterion_id = t.criterion_id')
              .where('t.ta_id = ? AND assignment_files.assignment_id = ?', @current_user.id, @assignment.id)
              .first) %>
      <% index = @files.find_index{|x| x.filename === assignmentfile.filename}.to_i %>
      first_file_id = <%= @files[index].id %>;
      first_file_path = '<%= @files[index].path %>/<%= @files[index].filename %>';
    <% else %>
      first_file_id = <%= @files[0].id %>;
      first_file_path = '<%= @files[0].path %>/<%= @files[0].filename %>';
      if (localStorage.getItem('assignment_id') === '<%= @assignment.id %>' && localStorage.getItem('file_path')) {
        var file = $('.file_item[data-path="' + localStorage.getItem('file_path') + '"]');
        if (file.length === 1) {
          first_file_id = file.data("id");
          first_file_path = file.data("path");
        }
      }
      if (first_file_id !== null && first_file_path !== null) {
        // for code viewer
        open_file(first_file_id, first_file_path, false);
        // for download modal
        open_file(first_file_id, first_file_path, true);
      }
    <% end %>
  <% end %>
</script>

<%= render partial: 'results/common/context_menu',
           formats: [:js],
           locals: {
               result: @result,
               annotation_categories: @assignment.annotation_categories.includes(:annotation_texts)
           } %>

app/views/results/set_released_to_students.js.erb
<% if @old_result %>
  window.location = "<%= edit_assignment_submission_result_path(id: @old_result.id) %>";
<% else %>
  window.location = "<%= edit_assignment_submission_result_path(id: @result.id) %>";
<% end %>